name: CI
on: [push]
jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Composer install
        uses: php-actions/composer@v6

      - run: curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
      - run: php phpcs.phar --standard=${{ github.workspace }}/test/phpcs/Symfony src

  phpunit:
    name: PHPUNIT
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Composer install
        uses: php-actions/composer@v6

      - name: PHPUnit
        uses: php-actions/phpunit@v3
        with:
          args: test
